// Mock Data for Construction App

export const MOCK_PROJECTS = [
  {
    id: 1,
    name: 'Downtown Office Complex',
    location: 'Downtown, NY',
    status: 'In Progress',
    progress: 65,
    startDate: '2024-01-15',
    endDate: '2024-08-30',
    budget: 850000,
    spent: 552500,
    workers: 18,
    tasks: 42,
  },
  {
    id: 2,
    name: 'Residential Building A',
    location: 'Brooklyn, NY',
    status: 'In Progress',
    progress: 48,
    startDate: '2024-02-01',
    endDate: '2024-10-15',
    budget: 1200000,
    spent: 576000,
    workers: 24,
    tasks: 67,
  },
  {
    id: 3,
    name: 'Shopping Mall Renovation',
    location: 'Queens, NY',
    status: 'Planning',
    progress: 15,
    startDate: '2024-03-01',
    endDate: '2024-12-31',
    budget: 2100000,
    spent: 315000,
    workers: 12,
    tasks: 89,
  },
  {
    id: 4,
    name: 'Bridge Infrastructure',
    location: 'Long Island City, NY',
    status: 'Completed',
    progress: 100,
    startDate: '2023-06-01',
    endDate: '2024-01-30',
    budget: 3500000,
    spent: 3485000,
    workers: 35,
    tasks: 156,
  },
  {
    id: 5,
    name: 'Hospital Expansion',
    location: 'Manhattan, NY',
    status: 'In Progress',
    progress: 72,
    startDate: '2023-11-01',
    endDate: '2024-09-30',
    budget: 5000000,
    spent: 3600000,
    workers: 42,
    tasks: 198,
  },
  {
    id: 6,
    name: 'School Sports Complex',
    location: 'Bronx, NY',
    status: 'On Hold',
    progress: 38,
    startDate: '2023-12-15',
    endDate: '2024-08-31',
    budget: 950000,
    spent: 361000,
    workers: 14,
    tasks: 54,
  },
];

export const MOCK_TASKS = [
  {
    id: 1,
    projectId: 1,
    title: 'Foundation Excavation',
    assignedTo: 'Mike Johnson',
    status: 'Completed',
    priority: 'High',
    dueDate: '2024-02-15',
    completedDate: '2024-02-14',
  },
  {
    id: 2,
    projectId: 1,
    title: 'Steel Frame Installation',
    assignedTo: 'Sarah Williams',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2024-04-30',
    progress: 60,
  },
  {
    id: 3,
    projectId: 1,
    title: 'Electrical Wiring',
    assignedTo: 'Robert Brown',
    status: 'Pending',
    priority: 'Medium',
    dueDate: '2024-05-15',
  },
  {
    id: 4,
    projectId: 2,
    title: 'Concrete Pouring',
    assignedTo: 'David Chen',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2024-04-20',
    progress: 45,
  },
  {
    id: 5,
    projectId: 2,
    title: 'Window Installation',
    assignedTo: 'Emma Davis',
    status: 'Pending',
    priority: 'Medium',
    dueDate: '2024-06-01',
  },
  {
    id: 6,
    projectId: 3,
    title: 'Site Surveying',
    assignedTo: 'James Wilson',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2024-03-31',
    progress: 85,
  },
];

export const MOCK_WORKERS = [
  {
    id: 1,
    name: 'Mike Johnson',
    role: 'Foreman',
    phone: '555-0101',
    email: 'mike.johnson@buildco.com',
    assignedProject: 'Downtown Office Complex',
    status: 'On-Site',
    team: 'Team A',
  },
  {
    id: 2,
    name: 'Sarah Williams',
    role: 'Structural Engineer',
    phone: '555-0102',
    email: 'sarah.williams@buildco.com',
    assignedProject: 'Downtown Office Complex',
    status: 'On-Site',
    team: 'Team A',
  },
  {
    id: 3,
    name: 'Robert Brown',
    role: 'Electrician',
    phone: '555-0103',
    email: 'robert.brown@buildco.com',
    assignedProject: 'Residential Building A',
    status: 'Off-Site',
    team: 'Team B',
  },
  {
    id: 4,
    name: 'David Chen',
    role: 'Carpenter',
    phone: '555-0104',
    email: 'david.chen@buildco.com',
    assignedProject: 'Residential Building A',
    status: 'On-Site',
    team: 'Team B',
  },
  {
    id: 5,
    name: 'Emma Davis',
    role: 'Mason',
    phone: '555-0105',
    email: 'emma.davis@buildco.com',
    assignedProject: 'Downtown Office Complex',
    status: 'On-Site',
    team: 'Team A',
  },
  {
    id: 6,
    name: 'James Wilson',
    role: 'Surveyor',
    phone: '555-0106',
    email: 'james.wilson@buildco.com',
    assignedProject: 'Shopping Mall Renovation',
    status: 'Off-Site',
    team: 'Team C',
  },
];

export const MOCK_MATERIALS = [
  { id: 1, name: 'Cement (Bags)', unit: 'Bag', quantity: 5000, min: 500, inStock: 2450, price: 12 },
  { id: 2, name: 'Steel Rods', unit: 'Ton', quantity: 250, min: 50, inStock: 45, price: 800 },
  { id: 3, name: 'Bricks', unit: 'Count', quantity: 500000, min: 50000, inStock: 87500, price: 0.35 },
  { id: 4, name: 'Gravel', unit: 'Cubic Meter', quantity: 1000, min: 100, inStock: 285, price: 45 },
  { id: 5, name: 'Plywood Sheets', unit: 'Sheet', quantity: 5000, min: 200, inStock: 125, price: 35 },
  { id: 6, name: 'Electrical Wire', unit: 'Meter', quantity: 50000, min: 5000, inStock: 8900, price: 2.5 },
];

export const MOCK_DASHBOARD_STATS = {
  activeProjects: 5,
  pendingTasks: 23,
  onSiteWorkers: 34,
  lowStockMaterials: 3,
  totalBudget: 13500000,
  totalSpent: 8329500,
  completedProjects: 1,
  teamMembers: 87,
};

export const MOCK_RECENT_PROJECTS = MOCK_PROJECTS.slice(0, 3);

export const MOCK_UPCOMING_TASKS = [
  {
    id: 1,
    title: 'Inspect Concrete Quality',
    project: 'Downtown Office Complex',
    dueDate: '2024-03-25',
    priority: 'High',
  },
  {
    id: 2,
    title: 'Order Glass Windows',
    project: 'Residential Building A',
    dueDate: '2024-03-26',
    priority: 'Medium',
  },
  {
    id: 3,
    title: 'Safety Training Session',
    project: 'Hospital Expansion',
    dueDate: '2024-03-27',
    priority: 'Medium',
  },
  {
    id: 4,
    title: 'Submit Progress Report',
    project: 'School Sports Complex',
    dueDate: '2024-03-28',
    priority: 'Low',
  },
];
